<a href="https://colab.research.google.com/github/sAI-2025/Jiohotstar_recomendationAgent/blob/main/JiohostarRecomder_system.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

# Read the CSV file
file_path = '/content/Jiohostar_srapped_data.csv'
try:
    # Added on_bad_lines='skip', sep=',' and skipinitialspace=True for robust and correct parsing
    df = pd.read_csv(file_path, engine='python', on_bad_lines='skip', sep=',', skipinitialspace=True)
    print(f"Successfully loaded data from {file_path}\n")
    df.columns = (
    df.columns
    .str.strip()           # Remove leading/trailing whitespace
    .str.lower()           # Convert to lowercase
    .str.replace(" ", "_") # Replace spaces with underscores
    )
    # Print columns
    print("Columns in the dataset:")
    print(df.columns.tolist())
    print("\n")

    # Check for null values
    print("Null values per column:")
    print(df.isnull().sum())
    print("\n")

    # Get value counts for all columns
    # print("Value counts for each column:")
    # for column in df.columns:
    #     print(f"--- {column} ---")
    #     print(df[column].value_counts(dropna=False))
    #     print("\n")

except FileNotFoundError:
    print(f"Error: The file '{file_path}' was not found. Please ensure it is uploaded to the Colab environment.")
except Exception as e:
    print(f"An error occurred while reading the CSV file or performing analysis: {e}")

Successfully loaded data from /content/Jiohostar_srapped_data.csv

Columns in the dataset:
['title', 'released_year', 'duration', 'genre', 'language', 'description']


Null values per column:
title            4
released_year    0
duration         0
genre            0
language         0
description      0
dtype: int64

In [ ]:
print("First value of each column:")
for column in df.columns:
    print(f"Column: {column}, First Value: {df[column].iloc[0]}")

First value of each column:
Column: title, First Value: Brahmāstra Part One: Shiva
Column: released_year, First Value: 2022
Column: duration, First Value: 2h 48m
Column: genre, First Value: Fantasy
Column: language, First Value: Hindi
Column: description, First Value: A journey of fantasy, action and romance comes to life as Shiva enters the Astraverse! He discovers true love and also, the power of fire within him.

In [ ]:
df.head(2)

,title,released_year,duration,genre,language,description
0,Brahmāstra Part One: Shiva,2022,2h 48m,Fantasy,Hindi,"A journey of fantasy, action and romance comes..."
1,Govinda Naam Mera,2022,2h 11m,Comedy,Comedy,"Wedged between a court case, a bad marriage an..."

In [ ]:
# Check if there are any duplicate rows
print(df.duplicated().sum())

0

In [ ]:
# Shape of the dataset
print("Shape:", df.shape)

# Column names
print("\nColumns:")
print(df.columns)

# Data types
print("\nData Types:")
print(df.dtypes)

# Missing values
print("\nMissing Values:")
print(df.isnull().sum())

# Number of unique values per column
print("\nUnique Values:")
print(df.nunique())

# Summary statistics
print("\nSummary Statistics:")
print(df.describe(include='all'))

Shape: (472, 6)

Columns:
Index(['title', 'released_year', 'duration', 'genre', 'language',
       'description'],
      dtype='object')

Data Types:
title            object
released_year     int64
duration         object
genre            object
language         object
description      object
dtype: object

Missing Values:
title            4
released_year    0
duration         0
genre            0
language         0
description      0
dtype: int64

Unique Values:
title            460
released_year     42
duration          98
genre             18
language          18
description      469
dtype: int64

Summary Statistics:
                                            title  released_year  duration  \
count                                         468     472.000000       472
unique                                        460            NaN        98
top     MS Dhoni: The Untold Story                           NaN  2h 26m
freq                                            3            NaN        14
mean                                          NaN    2013.565678       NaN
std                                           NaN       8.173018       NaN
min                                           NaN    1965.000000       NaN
25%                                           NaN    2012.750000       NaN
50%                                           NaN    2016.000000       NaN
75%                                           NaN    2018.000000       NaN
max                                           NaN    2023.000000       NaN

                  genre         language  \
count               472              472
unique               18               18
top     Action           Action
freq                154              146
mean                NaN              NaN
std                 NaN              NaN
min                 NaN              NaN
25%                 NaN              NaN
50%                 NaN              NaN
75%                 NaN              NaN
max                 NaN              NaN

                                              description
count                                                 472
unique                                                469
top     Why did Kattappa kill Amarendra Baahubali? Fin...
freq                                                    2
mean                                                  NaN
std                                                   NaN
min                                                   NaN
25%                                                   NaN
50%                                                   NaN
75%                                                   NaN
max                                                   NaN

In [ ]:
print(df.isnull().sum())

title            4
released_year    0
duration         0
genre            0
language         0
description      0
dtype: int64

In [ ]:
#Print the rows of null values
null_rows = df[df.isnull().any(axis=1)]
print(null_rows)

    title  released_year  duration            genre         language  \
266   NaN           2007  2h 9m     Action           Action
327   NaN           2000  2h 26m    Action           Action
391   NaN           1994  1h 51m    Action           Action
452   NaN           1997  2h 28m    Action           Action

                                           description
266  To avenge the acid attack on his sister, Dev t...
327  Jeeva takes Kiran under his wing and trains he...
391  A principled officer’s eldest son, Vikas is ki...
452  Raja, a small-time loafer falls head over heel...

In [ ]:
# Update missing titles
df.loc[266, 'title'] = 'Big Brother'
df.loc[327, 'title'] = 'Bichhoo'
df.loc[391, 'title'] = 'Aflatoon'

In [ ]:
df.shape

(472, 6)

In [ ]:
# Number of unique values per column
print("\nUnique Values:")
print(df.nunique())

Unique Values:
title            463
released_year     42
duration          98
genre             18
language          18
description      469
dtype: int64

In [ ]:
print("Value counts for each column:")
for column in df.columns:
    print(f"--- {column} ---")
    print(df[column].value_counts(dropna=False))
    print("\n")

Value counts for each column:
--- title ---
title
MS Dhoni: The Untold Story                   3
Raja Rani                                    2
Bang Bang                                    2
Khaidi No. 150                               2
Saamy 2                                      2
                                            ..
Aravindante Athidhikal                       1
Pink                                         1
Pisachi                                      1
Sammohanam                                   1
Vivegam                                      1
Name: count, Length: 464, dtype: int64


--- released_year ---
released_year
2017    69
2016    51
2018    48
2015    45
2019    33
2014    30
2022    26
2013    17
2021    16
2012    13
2020    12
2011    10
2010     9
2005     8
2006     8
2023     7
1999     7
2007     6
2001     6
2004     5
2008     4
2003     4
1998     4
1997     4
2002     4
2000     4
1995     4
2009     3
1993     2
1992     1
1967     1
1987     1
1990     1
1989     1
1994     1
1965     1
1978     1
1975     1
1985     1
1988     1
1982     1
1976     1
Name: count, dtype: int64


--- duration ---
duration
2h 26m      14
2h 13m      13
2h 3m       13
2h 10m      12
2h 14m      12
            ..
1h 31m       1
1h 8m        1
49m          1
31m          1
1h 14m       1
Name: count, Length: 98, dtype: int64


--- genre ---
genre
Action             154
Comedy              85
Drama               67
Thriller            50
Romance             48
Horror              21
Crime               13
Family               8
Biopic               7
Kids                 6
Animation            3
Mystery              3
Adventure            2
Fantasy              1
Documentary          1
Historical           1
Sports               1
Science Fiction      1
Name: count, dtype: int64


--- language ---
language
Action             146
Comedy              82
Drama               66
Thriller            48
Romance             46
Horror              21
Hindi               18
Crime               13
Family               8
Biopic               6
Kids                 6
Mystery              3
Animation            3
Adventure            2
Tamil                1
Historical           1
Sports               1
Science Fiction      1
Name: count, dtype: int64


--- description ---
description
Why did Kattappa kill Amarendra Baahubali? Find out the answer to this monumental question as you watch Amarendra's son in action in the sequel.                    2
When a series of mysterious events stirs pandemonium in a village, an eccentric cop Vikrant Rona sets out to solve the case wherein everyone is under the radar.    2
Young, middle-class boy Nani has to protect his sister-in-law, a transport official from a gangster, who runs an illegal transport business.                        2
A woman spends all her savings to buy a vintage car, only to discover that it is haunted by a revenge-hungry ghost.                                                 1
A bunch of amateurs set out to find a serial killer on the college campus, who uses social media as a tool. Can they find him before he claims his next victim?     1
                                                                                                                                                                   ..
To help a child in trouble, Lord Hanuman takes the avatar of a human being. However, when the evil asuras attack earth, he has to disclose his true identity.       1
When circumstances land a young Bharat in the position of the Chief Minister, he has to deal with corruption and enemies while attempting to reform politics.       1
While making a documentary on Alzheimer's disease, a man realises that there's more to his subject's inexplicable behaviour - something sinister and terrible.      1
Kumaran, an officer suffering from PTSD is on a serial killer’s trail. He is just about to nab the culprit when he discovers an abnormal truth.                     1
Bhoothnath revisits earth, and his after-life changes for good when he meets a brave boy, Akhrot. They team up to fight against Bhau, a corrupt politician.         1
Name: count, Length: 469, dtype: int64

In [ ]:
df.head(4)

,title,released_year,duration,genre,language,description
0,Brahmāstra Part One: Shiva,2022,2h 48m,Fantasy,Hindi,"A journey of fantasy, action and romance comes..."
1,Govinda Naam Mera,2022,2h 11m,Comedy,Comedy,"Wedged between a court case, a bad marriage an..."
2,Sita Ramam,2022,2h 33m,Romance,Romance,"On a letter-delivering task, Afreen learns of ..."
3,Ved,2022,2h 36m,Romance,Hindi,"Retreating from a failed romance, Satya drowns..."

In [ ]:
#Sorting the data based on the Relasesd year
df_sorted = df.sort_values(by='released_year', ascending=False)

In [ ]:
df_sorted.head(2)

,title,released_year,duration,genre,language,description
4,Selfiee,2023,2h 22m,Comedy,Comedy,RTO officer Om Prakash strikes a golden opport...
23,Romancham,2023,2h 10m,Comedy,Hindi,A game of Ouija board goes hilariously wrong w...

In [ ]:
# df_sorted["description"].value_counts(dropna=False)

In [ ]:
print("Value counts for each column:")
for column in df_sorted.columns:
    print(f"--- {column} ---")
    print(df_sorted[column].value_counts(dropna=False))
    print("\n")

Value counts for each column:
--- title ---
title
MS Dhoni: The Untold Story                   3
Bang Bang                                    2
Saamy 2                                      2
Raja Rani                                    2
Baahubali 2: The Conclusion                  2
                                            ..
Khatarnak Policewala                         1
Tubelight                                    1
DJ [Duvvada Jagannadham]                     1
Bayama Irukku                                1
Velaikkaran                                  1
Name: count, Length: 464, dtype: int64


--- released_year ---
released_year
2017    69
2016    51
2018    48
2015    45
2019    33
2014    30
2022    26
2013    17
2021    16
2012    13
2020    12
2011    10
2010     9
2006     8
2005     8
2023     7
1999     7
2007     6
2001     6
2004     5
2002     4
2008     4
2000     4
2003     4
1998     4
1997     4
1995     4
2009     3
1993     2
1994     1
1992     1
1990     1
1989     1
1988     1
1987     1
1985     1
1982     1
1978     1
1976     1
1975     1
1967     1
1965     1
Name: count, dtype: int64


--- duration ---
duration
2h 26m      14
2h 3m       13
2h 13m      13
2h 10m      12
2h 14m      12
            ..
2h 46m       1
1h 34m       1
2h 52m       1
3h 6m        1
2h 59m       1
Name: count, Length: 98, dtype: int64


--- genre ---
genre
Action             154
Comedy              85
Drama               67
Thriller            50
Romance             48
Horror              21
Crime               13
Family               8
Biopic               7
Kids                 6
Animation            3
Mystery              3
Adventure            2
Fantasy              1
Science Fiction      1
Historical           1
Documentary          1
Sports               1
Name: count, dtype: int64


--- language ---
language
Action             146
Comedy              82
Drama               66
Thriller            48
Romance             46
Horror              21
Hindi               18
Crime               13
Family               8
Biopic               6
Kids                 6
Animation            3
Mystery              3
Adventure            2
Tamil                1
Science Fiction      1
Historical           1
Sports               1
Name: count, dtype: int64


--- description ---
description
Young, middle-class boy Nani has to protect his sister-in-law, a transport official from a gangster, who runs an illegal transport business.                        2
When a series of mysterious events stirs pandemonium in a village, an eccentric cop Vikrant Rona sets out to solve the case wherein everyone is under the radar.    2
Why did Kattappa kill Amarendra Baahubali? Find out the answer to this monumental question as you watch Amarendra's son in action in the sequel.                    2
Siddharth and Trisha's happy married life takes a hit when they discover they are pregnant. Parenthood or splitsville - what is the way for them?                   1
An undercover agent is assigned to expose a drug racket and make a wanted drug lord come out of hiding. Will he succeed?                                            1
                                                                                                                                                                   ..
Taking us back to the 1962 Sino-Indian War; this is the story of a disabled man, popularly known as Tubelight, his love for his family and self-belief.             1
An undercover officer fights crime in the guise of a priest. Things take a turn when he falls in love with the daughter of a corrupt minister.                      1
When a group of friends find out that the wife of one of their friend is possessed, they decide to exorcise her!                                                    1
A rookie cop's first assignment turns into his life's biggest dilemma - to shoot or not. Does every choice have a price?                                            1
Set during the Indian Emergency, a simple housewife's life changes when she ventures into an area where residents are protesting against the government.            1
Name: count, Length: 469, dtype: int64

In [ ]:
# Find titles with more than one occurrence
duplicate_titles = df_sorted['title'].value_counts()
duplicate_titles = duplicate_titles[duplicate_titles > 1]

print(duplicate_titles)
print("="*1000)
# Print all rows with duplicate titles
duplicate_rows = df_sorted[df_sorted['title'].isin(duplicate_titles.index)]

print(duplicate_rows)

title
MS Dhoni: The Untold Story                   3
Bang Bang                                    2
Saamy 2                                      2
Vikrant Rona                                 2
Raja Rani                                    2
Baahubali 2: The Conclusion                  2
Khaidi No. 150                               2
Name: count, dtype: int64
========================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================
                                         title  released_year  duration  \
61   Vikrant Rona                                        2022  2h 25m
79   Vikrant Rona                                        2022  2h 25m
115  Saamy 2                                             2018  2h 28m
199  Saamy 2                                             2018  2h 28m
74   Baahubali 2: The Conclusion                         2017  2h 40m
110  Khaidi No. 150                                      2017  2h 17m
88   Baahubali 2: The Conclusion                         2017  2h 40m
307  Khaidi No. 150                                      2017  2h 17m
31   MS Dhoni: The Untold Story                          2016  2h 58m
105  MS Dhoni: The Untold Story                          2016  2h 57m
100  MS Dhoni: The Untold Story                          2016  2h 57m
350  Bang Bang                                           2014  2h 26m
83   Bang Bang                                           2014  2h 26m
388  Raja Rani                                           2014  2h 38m
158  Raja Rani                                           2013  2h 36m

               genre         language  \
61   Action           Action
79   Action           Tamil
115  Action           Action
199  Action           Action
74   Action           Action
110  Action           Action
88   Action           Action
307  Action           Action
31   Biopic           Biopic
105  Biopic           Biopic
100  Biopic           Biopic
350  Action           Action
83   Action           Action
388  Romance          Romance
158  Romance          Romance

                                           description
61   When a series of mysterious events stirs pande...
79   When a series of mysterious events stirs pande...
115  In this sequel to the superhit action thriller...
199  When Aarusaamy's son finds out the truth about...
74   Why did Kattappa kill Amarendra Baahubali? Unv...
110  Seenu escapes from prison and sends his lookal...
88   Why did Kattappa kill Amarendra Baahubali? Fin...
307  Kaththi Seenu, a convict on the run, meets his...
31   A tell-all tale about the life and times of In...
105  How did India get one of its favourite cricket...
100  A tell-all tale about the life and times of In...
350  The last thing bank receptionist Harleen wante...
83   Rajveer sets out to steal the world's most cov...
388  John and Regina only marry each other for the ...
158  John and Regina get married only to please the...

In [ ]:
duplicate_rows

,title,released_year,duration,genre,language,description
61,Vikrant Rona,2022,2h 25m,Action,Action,When a series of mysterious events stirs pande...
79,Vikrant Rona,2022,2h 25m,Action,Tamil,When a series of mysterious events stirs pande...
115,Saamy 2,2018,2h 28m,Action,Action,In this sequel to the superhit action thriller...
199,Saamy 2,2018,2h 28m,Action,Action,When Aarusaamy's son finds out the truth about...
74,Baahubali 2: The Conclusion,2017,2h 40m,Action,Action,Why did Kattappa kill Amarendra Baahubali? Unv...
110,Khaidi No. 150,2017,2h 17m,Action,Action,Seenu escapes from prison and sends his lookal...
88,Baahubali 2: The Conclusion,2017,2h 40m,Action,Action,Why did Kattappa kill Amarendra Baahubali? Fin...
307,Khaidi No. 150,2017,2h 17m,Action,Action,"Kaththi Seenu, a convict on the run, meets his..."
31,MS Dhoni: The Untold Story,2016,2h 58m,Biopic,Biopic,A tell-all tale about the life and times of In...
105,MS Dhoni: The Untold Story,2016,2h 57m,Biopic,Biopic,How did India get one of its favourite cricket...
100,MS Dhoni: The Untold Story,2016,2h 57m,Biopic,Biopic,A tell-all tale about the life and times of In...
350,Bang Bang,2014,2h 26m,Action,Action,The last thing bank receptionist Harleen wante...
83,Bang Bang,2014,2h 26m,Action,Action,Rajveer sets out to steal the world's most cov...
388,Raja Rani,2014,2h 38m,Romance,Romance,John and Regina only marry each other for the ...
158,Raja Rani,2013,2h 36m,Romance,Romance,John and Regina get married only to please the...

In [ ]:
# Step 1: Drop duplicate descriptions (keep first occurrence)
df_sorted = df_sorted.drop_duplicates(subset=['description'], keep='first')


# Step 2: Merge rows having the same title
def merge_descriptions(group):
    # Combine all descriptions into one string
    merged_description = " ".join(group['description'].dropna().astype(str))

    # Keep the first row's details
    row = group.iloc[0].copy()
    row['description'] = merged_description

    return row


# Apply merging based on title
df_sorted = (
    df_sorted
    .groupby('title', as_index=False, group_keys=False)
    .apply(merge_descriptions)
)


# Reset index after merging
df_sorted = df_sorted.reset_index(drop=True)

/tmp/ipykernel_1350/997409164.py:21: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(merge_descriptions)

In [ ]:
# Find titles with more than one occurrence
duplicate_titles = df_sorted['title'].value_counts()
duplicate_titles = duplicate_titles[duplicate_titles > 1]

print(duplicate_titles)
print("="*1000)
# Print all rows with duplicate titles
duplicate_rows = df_sorted[df_sorted['title'].isin(duplicate_titles.index)]

print(duplicate_rows)

Series([], Name: count, dtype: int64)
========================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================
Empty DataFrame
Columns: [title, released_year, duration, genre, language, description]
Index: []

In [ ]:
df_sorted.head()

,title,released_year,duration,genre,language,description
0,10 Endrathukulla,2015,2h 13m,Action,Action,A driving instructor is tasked by a criminal t...
1,10 Ka Dum,2015,2h 14m,Action,Action,"A local don hires a driver, Vikram, to escort ..."
2,1971 Beyond Borders,2017,1h 50m,Action,Action,"On a UN Mission, Colonel Mahadevan befriends a..."
3,2 Countries,2015,2h 28m,Comedy,Comedy,A con man gets lucky when he marries a wealthy...
4,24,2016,2h 37m,Thriller,Thriller,A scientist invents a time machine that his ev...
5,24 Ghante in Chennai,2013,1h 29m,Thriller,Thriller,"The lives of a superstar, a doctor and a journ..."
6,31st October,2016,1h 36m,Action,Action,In the aftermath of Indira Gandhi's assassinat...
7,8 Thottakal,2017,2h 7m,Thriller,Thriller,"Sathya, an honest cop, accidentally loses his ..."
8,A Gentleman,2017,2h 6m,Action,Action,A tale of mistaken identities where identical-...
9,A Paying Ghost,2015,2h,Comedy,Comedy,"Based on V.P. Kale's novel Badali, a kind-hear..."
10,A Thursday,2022,2h 8m,Thriller,Thriller,"Naina, a playschool teacher, takes 16 students..."
11,Aata - The Game of Fear,2016,1h 45m,Horror,Horror,Three aspiring software professional girls sta...
12,Aatma Ka Ghar,2012,1h 51m,Horror,Horror,Newlyweds Harsha and Mohini move into their ne...
13,Aatma Ka Ghar 2,2015,1h 30m,Horror,Horror,"Mohini and Harsha move to a different city, bu..."
14,Action Jackson,2014,2h 17m,Action,Action,A small-time crook Vishi has just about manage...
15,Adanga Maru,2018,2h 24m,Action,Action,A righteous cop's career and personal life tur...
16,Adi Kapyare Kootamani,2015,2h 6m,Comedy,Comedy,"Evading the eyes of the warden, Adhishta Laksh..."
17,Aflatoon,1994,1h 51m,Action,Action,"A principled officer’s eldest son, Vikas is ki..."
18,Aisha,2010,2h 6m,Romance,Romance,"Aisha thinks she is a perfect matchmaker, desp..."
19,Ajnabhi Se Pyar,2021,2h 9m,Drama,Drama,Despite being let down by societal stereotypes...
20,Akhil,2015,1h 39m,Action,Action,"To acquire a magical stone, a Russian gangster..."
21,Akira,2016,2h 10m,Action,Action,"Akira Sharma, a college student takes on four ..."
22,Aksar,2006,1h 33m,Romance,Romance,"Bound by an expensive pre-nuptial agreement, R..."
23,Anand,2004,2h 31m,Drama,Drama,Roopa calls off her wedding after her parents ...
24,Anbudan Appavukku,2016,2h 29m,Action,Action,Abhiram decides to seek revenge from Krishnamu...
25,Angrezi Medium,2020,2h 25m,Drama,Drama,"Champak, a simple Mithai-seller, will go to an..."
26,Anjani Putra,2017,1h 54m,Action,Action,A misunderstanding causes Viraj's mother to di...
27,Ankahee,2006,2h 27m,Thriller,Thriller,Dr Shekhar is happily married to Nandita. Trou...
28,Aravindante Athidhikal,2018,1h 55m,Drama,Drama,"Abandoned as a child near Mookambika Temple, A..."
29,Arjun Pandit,1999,2h 19m,Thriller,Thriller,Arjun keeps mum on a crime he witnessed. He fa...
30,Arjun Reddy,2017,2h 42m,Romance,Romance,A short-tempered yet brilliant young medical s...
31,Arjun Varma,2017,3h,Romance,Romance,A surgeon with a nasty temper turns to drugs a...
32,Arundhati,2014,2h 16m,Drama,Drama,A lookalike of warrior queen Jejamma takes bir...
33,Asuravettai,2017,2h 32m,Action,Action,A series of mysterious killings in the family ...
34,Athadu,2005,2h 52m,Action,Action,When an innocent person Pardhu dies instead of...
35,Atharintiki Daaredi,2013,2h 46m,Drama,Drama,Gautam promises to reconcile his aunt and her ...
36,Atrangi Re,2021,2h 16m,Romance,Hindi,Runaway Rinku gets forcefully married to an al...
37,Avan Ivan,2011,2h 11m,Comedy,Comedy,Walter and Samy constantly compete at pickpock...
38,Baadshaho,2017,2h 9m,Drama,Drama,An Indian queen seeks her bodyguard's help to ...
39,Baaghi 2,2018,2h 14m,Action,Action,A tough army officer searches for his ex-lover...
40,Baaghi 3,2020,2h 24m,Action,Action,"In a twisted turn of events, when a group of d..."
41,Baahubali - The Beginning,2015,2h 32m,Action,Action,Darkness befalls the Mahishmati kingdom after ...
42,Baahubali 2: The Conclusion,2017,2h 40m,Action,Action,Why did Kattappa kill Amarendra Baahubali? Unv...
43,Baba Baby O,2022,2h 9m,Romance,Romance,"In his 40s, Megh becomes a single father with ..."
44,Babli Bouncer,2022,1h 57m,Comedy,Hindi,"A first-of-its-kind for her village, Babli tak..."
45,Baby,2015,2h 33m,Action,Hindi,"Post 26/11 Mumbai attacks, a special intellige..."
46,Bade Ghar Ki Beti,1989,2h 21m,Family,Family,Poor girl Mala marries rich boy Gopal at the b...
47,Bade Miyan Chote Miyan,1998,2h 20m,Comedy,Comedy,Unaware that their lookalikes are using their ...
48,Badhaai Ho,2018,2h 3m,Comedy,Comedy,Getting a new sibling at 25 is the last thing ...
49,Badmaash,2016,1h 38m,Romance,Romance,Vijay and Priya are head over heels in love wi...
50,Badrinath Yatra,1967,2h,Crime,Crime,Satyavati's pilgrim to Badrinath gets cancelle...
51,Bagh Bandi Khela,2018,2h 27m,Thriller,Thriller,Three stories revolving around three individua...
52,Baghban,2003,2h 50m,Drama,Drama,Elderly couple Raj and Priya wish for their ch...
53,Bajrangi Bhaijaan,2015,2h 32m,Drama,Drama,"A simple guy, Pawan Kumar Chaturvedi, who is a..."

In [ ]:
# Sort by released year (ascending order)
df_sorted = df_sorted.sort_values(by='released_year', ascending=True)

# Reset index after sorting
df_sorted = df_sorted.reset_index(drop=True)

# Display first rows
df_sorted.head()

,title,released_year,duration,genre,language,description
0,Waqt,1965,2h 58m,Drama,Drama,"Separated in childhood, three brothers come to..."
1,Badrinath Yatra,1967,2h,Crime,Crime,Satyavati's pilgrim to Badrinath gets cancelle...
2,Zameer,1975,2h 9m,Action,Action,Thakur Maharaj Singh loses his son during a ro...
3,Chhoti Si Baat,1976,1h 58m,Comedy,Comedy,A shy Arun takes the help of a retired colonel...
4,Main Tulsi Tere Aangan Ki,1978,2h 26m,Drama,Drama,"Sanjukta wholeheartedly raises Ajay, her husba..."

In [ ]:
df_sorted.shape

(461, 6)

In [ ]:
df_sorted.describe()

       released_year
count     461.000000
mean     2013.533623
std         8.214082
min      1965.000000
25%      2012.000000
50%      2016.000000
75%      2018.000000
max      2023.000000

In [ ]:
df_sorted.nunique()

title            461
released_year     42
duration          97
genre             18
description      461
dtype: int64

In [ ]:
# Check data types of each column
print("Data types of each column in df_sorted:")
print(df_sorted.dtypes)

Data types of each column in df_sorted:
title            object
released_year     int64
duration         object
genre            object
description      object
dtype: object

In [ ]:
# Value counts for selected columns

print("Genre counts:")
print(df_sorted['genre'].value_counts())

print("=" * 100)

print("Language counts:")
print(df_sorted['language'].value_counts())

print("=" * 100)

print("Released year counts:")
print(df_sorted['released_year'].value_counts())

Genre counts:
genre
Action             146
Comedy              85
Drama               67
Thriller            50
Romance             47
Horror              21
Crime               13
Family               8
Kids                 6
Biopic               5
Animation            3
Mystery              3
Adventure            2
Sports               1
Documentary          1
Fantasy              1
Historical           1
Science Fiction      1
Name: count, dtype: int64
====================================================================================================
Language counts:
language
Action             139
Comedy              82
Drama               66
Thriller            48
Romance             45
Horror              21
Hindi               18
Crime               13
Family               8
Kids                 6
Biopic               4
Animation            3
Mystery              3
Adventure            2
Sports               1
Historical           1
Science Fiction      1
Name: count, dtype: int64
====================================================================================================
Released year counts:
released_year
2017    65
2016    49
2018    47
2015    45
2019    33
2014    29
2022    25
2013    16
2021    16
2012    13
2020    12
2011    10
2010     9
2005     8
2006     8
1999     7
2023     7
2001     6
2007     6
2004     5
2008     4
2002     4
1995     4
1998     4
2003     4
2000     4
1997     3
2009     3
1993     2
1988     1
1989     1
1978     1
1976     1
1975     1
1967     1
1965     1
1987     1
1985     1
1982     1
1990     1
1992     1
1994     1
Name: count, dtype: int64

In [ ]:
# Check if genre and language columns have the same values in the same order
same_values = (df_sorted['genre'] == df_sorted['language']).all()

print(same_values)

False

In [ ]:
different_rows = df_sorted[df_sorted['genre'] != df_sorted['language']]

print(different_rows[['genre', 'language']])

               genre         language
178  Action           Hindi
303  Comedy           Hindi
385  Thriller         Hindi
411  Drama            Hindi
414  Romance          Hindi
420  Action           Hindi
422  Documentary      Hindi
425  Action           Hindi
433  Romance          Hindi
435  Action           Hindi
441  Biopic           Hindi
442  Thriller         Hindi
444  Fantasy          Hindi
448  Action           Hindi
449  Comedy           Hindi
450  Action           Hindi
459  Comedy           Hindi
460  Action           Hindi

In [ ]:
df_sorted.drop(columns=['language'], inplace=True)

In [ ]:
df_sorted.head(5)

,title,released_year,duration,genre,description
0,Waqt,1965,2h 58m,Drama,"Separated in childhood, three brothers come to..."
1,Badrinath Yatra,1967,2h,Crime,Satyavati's pilgrim to Badrinath gets cancelle...
2,Zameer,1975,2h 9m,Action,Thakur Maharaj Singh loses his son during a ro...
3,Chhoti Si Baat,1976,1h 58m,Comedy,A shy Arun takes the help of a retired colonel...
4,Main Tulsi Tere Aangan Ki,1978,2h 26m,Drama,"Sanjukta wholeheartedly raises Ajay, her husba..."

In [ ]:
df_sorted.describe()

       released_year
count     461.000000
mean     2013.533623
std         8.214082
min      1965.000000
25%      2012.000000
50%      2016.000000
75%      2018.000000
max      2023.000000

In [ ]:
df_sorted.to_csv('Jiohostar_preprocessedData.csv', index=False)
print("Preprocessed data saved to 'data_preprocessed.csv'")

Preprocessed data saved to 'data_preprocessed.csv'